spring.application.name=hotelsearch

spring.datasource.url=jdbc:oracle:thin:@${SPRING_ORACLESQL_HOST:localhost}:${SPRING_ORACLESQL_PORT:1521}/FREEPDB1
spring.datasource.username=hotelapp
spring.datasource.password=${oracle_user_password:}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=create-drop

resilience4j.retry.instances.outboxRetry.max-attempts=3
resilience4j.retry.instances.outboxRetry.wait-duration=2s
resilience4j.retry.instances.outboxRetry.retry-exceptions=java.sql.SQLException,com.mindata.hotelsearch.infrastructure.adapter.exception.PersistenceOutboxException,java.lang.Exception

resilience4j.circuitbreaker.instances.outboxCB.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.outboxCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.outboxCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.outboxCB.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.outboxCB.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.outboxCB.minimum-number-of-calls=5

resilience4j.retry.instances.updateSearchReservationRetry.max-attempts=3
resilience4j.retry.instances.updateSearchReservationRetry.wait-duration=2s
resilience4j.retry.instances.updateSearchReservationRetry.retry-exceptions=java.lang.Exception

resilience4j.circuitbreaker.instances.updateSearchReservationCB.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.updateSearchReservationCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.updateSearchReservationCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.updateSearchReservationCB.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.updateSearchReservationCB.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.updateSearchReservationCB.minimum-number-of-calls=5

resilience4j.ratelimiter.instances.saveSearchReservationApiLimiter.limit-for-period=5
resilience4j.ratelimiter.instances.saveSearchReservationApiLimiter.limit-refresh-period=1s
resilience4j.ratelimiter.instances.saveSearchReservationApiLimiter.timeout-duration=500ms

resilience4j.ratelimiter.instances.getSearchReservationApiLimiter.limit-for-period=5
resilience4j.ratelimiter.instances.getSearchReservationApiLimiter.limit-refresh-period=1s
resilience4j.ratelimiter.instances.getSearchReservationApiLimiter.timeout-duration=500ms

spring.kafka.bootstrap-servers=${SPRING_KAFKA_HOST:localhost}:${SPRING_KAFKA_PORT:29092}
spring.kafka.producer.retries=3
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.acks=all
spring.kafka.producer.properties.max.in.flight.requests.per.connection= 5
spring.kafka.consumer.group-id=hotel-search-consumer-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.mindata.hotelsearch.infrastructure.adapter.kafka.event
spring.kafka.consumer.enable-auto-commit=true
spring.kafka.listener.concurrency=3

kafka.topic.searches=hotel_availability_searches
kafka.search.update.count.dlq-topic=hotel_availability_searches_update_count_dlq
